graphql:
  servlet:
    max-query-depth: 5
  playground:
    tabs:
      - name: Bank Account sample query
        query: classpath:playground/share_market.graphql
        variables: classpath:playground/variables.json

voyager:
  cdn:
    enabled: true

server:
  port: 8081
